version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app

workflows:
  on_commit:
    jobs:
      - build_and_test